import brush from "@/assets/images/brush.svg"
import print from "@/assets/images/print.svg"
import latest from "@/assets/images/latest-technology.svg"
import different from "@/assets/images/different-countries.svg"
import eco from "@/assets/images/eco.svg"
import production from "@/assets/images/production.svg"
import megaMenuIcon from "@/assets/images/mega-menu-icon.svg"
import bars from "@/assets/images/bars.svg"
import xmark from "@/assets/images/xmark.svg"
import chevronDown from "@/assets/images/chevron.svg"
import circleIcon from "@/assets/images/circle-icon.svg"
import longArrow from "@/assets/images/long-arrow.svg"
import leftArrow from "@/assets/images/arrow-left.svg"
import rightArrow from "@/assets/images/arrow-right.svg"
import mailIcon from "@/assets/images/icons/mail.svg"
import locationIcon from "@/assets/images/icons/location.svg"

export {brush, print, latest, different, eco, production, megaMenuIcon, bars, xmark, chevronDown, circleIcon, longArrow, leftArrow, rightArrow, mailIcon, locationIcon }